DROP TABLE IF EXISTS pokemon;

CREATE TABLE pokemon(
    id INTEGER NOT NULL PRIMARY KEY,
    name VARCHAR(64),
    types VARCHAR(64),
    dexEntry text,
    sprite VARCHAR(256)
);

INSERT INTO pokemon(id, name, types, dexEntry, sprite) VALUES
    (1, 'bulbasaur', 'grass, poison', 'While it is young, it uses the nutrients that are stored in the seed on its back in order to grow.', '1.png'),
    (2, 'ivysaur', 'grass, poison', 'Exposure to sunlight adds to its strength. Sunlight also makes the bud on its back grow larger.', '2.png'),
    (3, 'venusaur', 'grass, poison', 'Huge amounts of pollen burst from it with the force of a volcanic eruption. Breathing in too much of the pollen can cause fainting.', '3.png'),
    (4, 'charmander', 'fire', 'From the time it is born, a flame burns at the tip of its tail. Its life would end if the flame were to go out.', '4.png'),
    (5, 'charmeleon', 'fire', 'If it becomes agitated during battle, it spouts intense flames, incinerating its surroundings.', '5.png'),
    (6, 'charizard', 'fire, flying', 'The flame inside its body burns hotter than 3,600 degrees Fahrenheit. When Charizard roars, that temperature climbs even higher.', '6.png'),
    (7, 'squirtle', 'water', 'When it feels threatened, it draws its limbs inside its shell and sprays water from its mouth.', '7.png'),
    (8, 'wartortle', 'water', 'It cleverly controls its furry ears and tail to maintain its balance while swimming.', '8.png'),
    (9, 'blastoise', 'water', 'Water fired from this Pokémon’s central main cannon has enough power to blast a hole into a mountain.', '9.png'),
    (10, 'caterpie', 'bug', 'Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls.', '10.png'),
    (11, 'metapod', 'bug', 'Even though it is encased in a sturdy shell, the body inside is tender. It can’t withstand a harsh attack.', '11.png'),
    (12, 'butterfree', 'bug, flying', 'Once it has opponents trapped in a tornado that could blow away a 10-ton truck, it finishes them off with its poisonous scales.', '12.png'),
    (13, 'weedle', 'bug, poison', 'Beware of the sharp stinger on its head. It hides in grass and bushes where it eats leaves.', '13.png'),
    (14, 'kakuna', 'bug, poison', 'Able to move only slightly. When endangered, it may stick out its stinger and poison its enemy.', '14.png'),
    (15, 'beedrill', 'bug, poison', 'Its legs have become poison stingers. It stabs its prey repeatedly with the stingers on its limbs, dealing the final blow with the stinger on its rear.', '15.png'),
    (16, 'pidgey', 'normal, flying', 'Very docile. If attacked, it will often kick up sand to protect itself rather than fight back.', '16.png'),
    (17, 'pidgeotto', 'normal, flying', 'This Pokémon is full of vitality. It constantly flies around its large territory in search of prey.', '17.png'),
    (18, 'pidgeot', 'normal, flying', 'With its muscular strength now greatly increased, it can fly continuously for two weeks without resting.', '18.png'),
    (19, 'rattata', 'normal', 'Will chew on anything with its fangs. If you see one, you can be certain that 40 more live in the area.', '19.png'),
    (20, 'raticate', 'normal', 'Its hind feet are webbed. They act as flippers, so it can swim in rivers and hunt for prey.', '20.png'),
    (21, 'spearow', 'normal, flying', 'Inept at flying high. However, it can fly around very fast to protect its territory.', '21.png'),
    (22, 'fearow', 'normal, flying', 'A Pokémon that dates back many years. If it senses danger, it flies high and away, instantly.', '22.png'),
    (23, 'ekans', 'poison', 'The older it gets, the longer it grows. At night, it wraps its long body around tree branches to rest.', '23.png'),
    (24, 'arbok', 'poison', 'The frightening patterns on its belly have been studied. Six variations have been confirmed.', '24.png'),
    (25, 'pikachu', 'electric', 'When it smashes its opponents with its bolt- shaped tail, it delivers a surge of electricity equivalent to a lightning strike.', '25.png'),
    (26, 'raichu', 'electric', 'This Pokémon rides on its tail while it uses its psychic powers to levitate. It attacks with star-shaped thunderbolts.', '26.png'),
    (27, 'sandshrew', 'ground', 'It lives in snowy mountains on southern islands. When a blizzard rolls in, this Pokémon hunkers down in the snow to avoid getting blown away.', '27.png'),
    (28, 'sandslash', 'ground', 'Many people climb snowy mountains, hoping to see the icy spikes of these Pokémon glistening in the light of dawn.', '28.png'),
    (29, 'nidoran-f', 'poison', 'A mild-mannered Pokémon that does not like to fight. Beware—its small horn secretes venom.', '29.png'),
    (30, 'nidorina', 'poison', 'When resting deep in its burrow, its barbs always retract. This is proof that it is relaxed.', '30.png'),
    (31, 'nidoqueen', 'poison, ground', 'Tough scales cover the sturdy body of this Pokémon. It appears that the scales grow in cycles.', '31.png'),
    (32, 'nidoran-m', 'poison', 'Its large ears are always kept upright. If it senses danger, it will attack with a poisonous sting.', '32.png'),
    (33, 'nidorino', 'poison', 'Its horn contains venom. If it stabs an enemy with the horn, the impact makes the poison leak out.', '33.png'),
    (34, 'nidoking', 'poison, ground', 'Its steel-like hide adds to its powerful tackle. Its horns are so hard, they can pierce a diamond.', '34.png'),
    (35, 'clefairy', 'fairy', 'Its adorable behavior and cry make it highly popular. However, this cute Pokémon is rarely found.', '35.png'),
    (36, 'clefable', 'fairy', 'Their ears are sensitive enough to hear a pin drop from over a mile away, so they’re usually found in quiet places.', '36.png'),
    (37, 'vulpix', 'fire', 'If you observe its curly hairs through a microscope, you’ll see small ice particles springing up.', '37.png'),
    (38, 'ninetales', 'fire', 'While it will guide travelers who get lost on a snowy mountain down to the mountain’s base, it won’t forgive anyone who harms nature.', '38.png'),
    (39, 'jigglypuff', 'normal, fairy', 'By freely changing the wavelength of its voice, Jigglypuff sings a mysterious melody sure to make any listener sleepy.', '39.png'),
    (40, 'wigglytuff', 'normal, fairy', 'It’s proud of its fur, which is fine and delicate. In particular, the curl on its forehead has a texture that’s perfectly heavenly.', '40.png'),
    (41, 'zubat', 'poison, flying', 'Emits ultrasonic cries while it flies. They act as a sonar used to check for objects in its way.', '41.png'),
    (42, 'golbat', 'poison, flying', 'It attacks in a stealthy manner, without warning. Its sharp fangs are used to bite and to suck blood.', '42.png'),
    (43, 'oddish', 'grass, poison', 'During the day, it stays in the cold underground to avoid the sun. It grows by bathing in moonlight.', '43.png'),
    (44, 'gloom', 'grass, poison', 'What appears to be drool is actually sweet honey. It is very sticky and clings stubbornly if touched.', '44.png'),
    (45, 'vileplume', 'grass, poison', 'The larger its petals, the more toxic pollen it contains. Its big head is heavy and hard to hold up.', '45.png'),
    (46, 'paras', 'bug, grass', 'Burrows under the ground to gnaw on tree roots. The mushrooms on its back absorb most of the nutrition.', '46.png'),
    (47, 'parasect', 'bug, grass', 'The bug host is drained of energy by the mushroom on its back. The mushroom appears to do all the thinking.', '47.png'),
    (48, 'venonat', 'bug, poison', 'Its large eyes act as radar. In a bright place, you can see that they are clusters of many tiny eyes.', '48.png'),
    (49, 'venomoth', 'bug, poison', 'The powdery scales on its wings are hard to remove from skin. They also contain poison that leaks out on contact.', '49.png'),
    (50, 'diglett', 'ground', 'Its three hairs change shape depending on Diglett’s mood. They’re a useful communication tool among these Pokémon.', '50.png'),
    (51, 'dugtrio', 'ground', 'These Diglett triplets dig over 60 miles below sea level. No one knows what it’s like underground.', '51.png'),
    (52, 'meowth', 'normal', 'These daring Pokémon have coins on their foreheads. Darker coins are harder, and harder coins garner more respect among Meowth.', '52.png'),
    (53, 'persian', 'normal', 'This Pokémon is one tough opponent. Not only does it have formidable physical abilities, but it’s also not above fighting dirty.', '53.png'),
    (54, 'psyduck', 'water', 'As Psyduck gets stressed out, its headache gets progressively worse. It uses intense psychic energy to overwhelm those around it.', '54.png'),
    (55, 'golduck', 'water', 'Old tales tell of Golduck punishing those that defiled its river. The guilty were dragged into the water and taken away.', '55.png'),
    (56, 'mankey', 'fighting', 'An agile Pokémon that lives in trees. It angers easily and will not hesitate to attack anything.', '56.png'),
    (57, 'primeape', 'fighting', 'It stops being angry only when nobody else is around. To view this moment is very difficult.', '57.png'),
    (58, 'growlithe', 'fire', 'Extremely loyal, it will fearlessly bark at any opponent to protect its own Trainer from harm.', '58.png'),
    (59, 'arcanine', 'fire', 'A Pokémon that has long been admired for its beauty. It runs agilely as if on wings.', '59.png'),
    (60, 'poliwag', 'water', 'In rivers with fast-flowing water, this Pokémon will cling to a rock by using its thick lips, which act like a suction cup.', '60.png'),
    (61, 'poliwhirl', 'water', 'This Pokémon’s sweat is a slimy mucus. When captured, Poliwhirl can slither from its enemies’ grasp and escape.', '61.png'),
    (62, 'poliwrath', 'water, fighting', 'Poliwrath is skilled at both swimming and martial arts. It uses its well-trained arms to dish out powerful punches.', '62.png'),
    (63, 'abra', 'psychic', 'Abra can teleport in its sleep. Apparently the more deeply Abra sleeps, the farther its teleportations go.', '63.png'),
    (64, 'kadabra', 'psychic', 'This Pokémon’s telekinesis is immensely powerful. To prepare for evolution, Kadabra stores up psychic energy in the star on its forehead.', '64.png'),
    (65, 'alakazam', 'psychic', 'Alakazam wields potent psychic powers. It’s said that this Pokémon used these powers to create the spoons it holds.', '65.png'),
    (66, 'machop', 'fighting', 'Always brimming with power, it passes time by lifting boulders. Doing so makes it even stronger.', '66.png'),
    (67, 'machoke', 'fighting', 'Its formidable body never gets tired. It helps people by doing work such as the moving of heavy goods.', '67.png'),
    (68, 'machamp', 'fighting', 'With four arms that react more quickly than it can think, it can execute many punches at once.', '68.png'),
    (69, 'bellsprout', 'grass, poison', 'Prefers hot and humid places. It ensnares tiny bugs with its vines and devours them.', '69.png'),
    (70, 'weepinbell', 'grass, poison', 'When hungry, it swallows anything that moves. Its hapless prey is dissolved by strong acids.', '70.png'),
    (71, 'victreebel', 'grass, poison', 'Lures prey with the sweet aroma of honey. Swallowed whole, the prey is dissolved in a day, bones and all.', '71.png'),
    (72, 'tentacool', 'water, poison', 'This Pokémon is mostly made of water. A Tentacool out in the ocean is very hard to spot, because its body blends in with the sea.', '72.png'),
    (73, 'tentacruel', 'water, poison', 'Its 80 tentacles can stretch and shrink freely. Tentacruel ensnares prey in a net of spread-out tentacles, delivering venomous stings to its catch.', '73.png'),
    (74, 'geodude', 'rock, ground', 'Its stone head is imbued with electricity and magnetism. If you carelessly step on one, you’ll be in for a painful shock.', '74.png'),
    (75, 'graveler', 'rock, ground', 'When it comes rolling down a mountain path, anything in its way gets zapped by electricity and sent flying.', '75.png'),
    (76, 'golem', 'rock, ground', 'Once it sheds its skin, its body turns tender and whitish. Its hide hardens when it’s exposed to air.', '76.png'),
    (77, 'ponyta', 'fire', 'This Pokémon will look into your eyes and read the contents of your heart. If it finds evil there, it promptly hides away.', '77.png'),
    (78, 'rapidash', 'fire', 'The fastest runner becomes the leader, and it decides the herd’s pace and direction of travel.', '78.png'),
    (79, 'slowpoke', 'water, psychic', 'When this Pokémon’s tail is soaked in water, sweetness seeps from it. Slowpoke uses this trait to lure in and fish up other Pokémon.', '79.png'),
    (80, 'slowbro', 'water, psychic', 'If this Pokémon squeezes the tongue of the Shellder biting it, the Shellder will launch a toxic liquid from the tip of its shell.', '80.png'),
    (81, 'magnemite', 'electric, steel', 'It subsists on electricity. As Magnemite flies, it emits electromagnetic waves from the units on each side of its body.', '81.png'),
    (82, 'magneton', 'electric, steel', 'This Pokémon is constantly putting out a powerful magnetic force. Most computers go haywire when a Magneton approaches.', '82.png'),
    (83, 'farfetchd', 'normal, flying', 'They use a plant stalk as a weapon, but not all of them use it in the same way. Several distinct styles of stalk fighting have been observed.', '83.png'),
    (84, 'doduo', 'normal, flying', 'Its short wings make flying difficult. Instead, this Pokémon runs at high speed on developed legs.', '84.png'),
    (85, 'dodrio', 'normal, flying', 'One of Doduo’s two heads splits to form a unique species. It runs close to 40 mph in prairies.', '85.png'),
    (86, 'seel', 'water', 'Loves freezing-cold conditions. Relishes swimming in a frigid climate of around 14 degrees Fahrenheit.', '86.png'),
    (87, 'dewgong', 'water, ice', 'Its entire body is a snowy white. Unharmed by even intense cold, it swims powerfully in icy waters.', '87.png'),
    (88, 'grimer', 'poison', 'Made of congealed sludge. It smells too putrid to touch. Even weeds won’t grow in its path.', '88.png'),
    (89, 'muk', 'poison', 'Smells so awful, it can cause fainting. Through degeneration of its nose, it lost its sense of smell.', '89.png'),
    (90, 'shellder', 'water', 'Its hard shell repels any kind of attack. It is vulnerable only when its shell is open.', '90.png'),
    (91, 'cloyster', 'water, ice', 'Once it slams its shell shut, it is impossible to open, even by those with superior strength.', '91.png'),
    (92, 'gastly', 'ghost, poison', 'With its gas-like body, it can sneak into any place it desires. However, it can be blown away by wind.', '92.png'),
    (93, 'haunter', 'ghost, poison', 'If you get the feeling of being watched in darkness when nobody is around, Haunter is there.', '93.png'),
    (94, 'gengar', 'ghost, poison', 'It lays traps, hoping to steal the lives of those it catches. If you stand in front of its mouth, you’ll hear your loved ones’ voices calling out to you.', '94.png'),
    (95, 'onix', 'rock, ground', 'It rapidly bores through the ground at 50 mph by squirming and twisting its massive, rugged body.', '95.png'),
    (96, 'drowzee', 'psychic', 'If you sleep by it all the time, it will sometimes show you dreams it had eaten in the past.', '96.png'),
    (97, 'hypno', 'psychic', 'Avoid eye contact if you come across one. It will try to put you to sleep by using its pendulum.', '97.png'),
    (98, 'krabby', 'water', 'If it senses danger approaching, it cloaks itself with bubbles from its mouth so it will look bigger.', '98.png'),
    (99, 'kingler', 'water', 'The bubbles it spews out are strongly alkaline. Any opponents hit by them will have their bodies quickly melted away.', '99.png'),
    (100, 'voltorb', 'electric', 'It is said to camouflage itself as a Poké Ball. It will self-destruct with very little stimulus.', '100.png'),
    (101, 'electrode', 'electric', 'Stores electrical energy inside its body. Even the slightest shock could trigger a huge explosion.', '101.png'),
    (102, 'exeggcute', 'grass, psychic', 'These Pokémon get nervous when they’re not in a group of six. The minute even one member of the group goes missing, Exeggcute become cowardly.', '102.png'),
    (103, 'exeggutor', 'grass, psychic', 'When they work together, Exeggutor’s three heads can put out powerful psychic energy. Cloudy days make this Pokémon sluggish.', '103.png'),
    (104, 'cubone', 'ground', 'This Pokémon wears the skull of its deceased mother. Sometimes Cubone’s dreams make it cry, but each tear Cubone sheds makes it stronger.', '104.png'),
    (105, 'marowak', 'ground', 'When this Pokémon evolved, the skull of its mother fused to it. Marowak’s temperament also turned vicious at the same time.', '105.png'),
    (106, 'hitmonlee', 'fighting', 'The legs freely contract and stretch. The stretchy legs allow it to hit a distant foe with a rising kick.', '106.png'),
    (107, 'hitmonchan', 'fighting', 'Its punches slice the air. However, it seems to need a short break after fighting for three minutes.', '107.png'),
    (108, 'lickitung', 'normal', 'Bug Pokémon are Lickitung’s main food source. This Pokémon paralyzes its prey with a lick from its long tongue, then swallows the prey whole.', '108.png'),
    (109, 'koffing', 'poison', 'It adores polluted air. Some claim that Koffing used to be more plentiful in the Galar region than they are now.', '109.png'),
    (110, 'weezing', 'poison', 'Long ago, during a time when droves of factories fouled the air with pollution, Weezing changed into this form for some reason.', '110.png'),
    (111, 'rhyhorn', 'ground, rock', 'It can remember only one thing at a time. Once it starts rushing, it forgets why it started.', '111.png'),
    (112, 'rhydon', 'ground, rock', 'Protected by an armor-like hide, it is capable of living in molten lava of 3,600 degrees Fahrenheit.', '112.png'),
    (113, 'chansey', 'normal', 'This species was once very slow. To protect their eggs from other creatures, these Pokémon became able to flee quickly.', '113.png'),
    (114, 'tangela', 'grass', 'The vines of a Tangela have a distinct scent. In some parts of Galar, Tangela vines are used as herbs.', '114.png'),
    (115, 'kangaskhan', 'normal', 'There are records of a lost human child being raised by a childless Kangaskhan.', '115.png'),
    (116, 'horsea', 'water', 'They swim with dance-like motions and cause whirlpools to form. Horsea compete to see which of them can generate the biggest whirlpool.', '116.png'),
    (117, 'seadra', 'water', 'Seadra’s mouth is slender, but its suction power is strong. In an instant, Seadra can suck in food that’s larger than the opening of its mouth.', '117.png'),
    (118, 'goldeen', 'water', 'Its dorsal and pectoral fins are strongly developed like muscles. It can swim at a speed of five knots.', '118.png'),
    (119, 'seaking', 'water', 'Using its horn, it bores holes in riverbed boulders, making nests to prevent its eggs from washing away.', '119.png'),
    (120, 'staryu', 'water', 'Fish Pokémon nibble at it, but Staryu isn’t bothered. Its body regenerates quickly, even if part of it is completely torn off.', '120.png'),
    (121, 'starmie', 'water, psychic', 'Starmie swims by spinning its body at high speed. As this Pokémon cruises through the ocean, it absorbs tiny plankton.', '121.png'),
    (122, 'mr-mime', 'psychic, fairy', 'It’s known for its top-notch pantomime skills. It protects itself from all sorts of attacks by emitting auras from its fingers to create walls.', '122.png'),
    (123, 'scyther', 'bug, flying', 'If you come across an area in a forest where a lot of the trees have been cut down, what you’ve found is a Scyther’s territory.', '123.png'),
    (124, 'jynx', 'ice, psychic', 'Appears to move to a rhythm of its own, as if it were dancing. It wiggles its hips as it walks.', '124.png'),
    (125, 'electabuzz', 'electric', 'If a major power outage occurs, it is certain that this Pokémon has eaten electricity at a power plant.', '125.png'),
    (126, 'magmar', 'fire', 'Born in an active volcano. Its body is always cloaked in flames, so it looks like a big ball of fire.', '126.png'),
    (127, 'pinsir', 'bug', 'This Pokémon clamps its pincers down on its prey and then either splits the prey in half or flings it away.', '127.png'),
    (128, 'tauros', 'normal', 'The Tauros of the Galar region are volatile in nature, and they won’t allow people to ride on their backs.', '128.png'),
    (129, 'magikarp', 'water', 'This weak and pathetic Pokémon gets easily pushed along rivers when there are strong currents.', '129.png'),
    (130, 'gyarados', 'water, flying', 'Once it begins to rampage, a Gyarados will burn everything down, even in a harsh storm.', '130.png'),
    (131, 'lapras', 'water, ice', 'It surrounds itself with a huge ring of gathered ice particles. It uses the ring to smash any icebergs that might impede its graceful swimming.', '131.png'),
    (132, 'ditto', 'normal', 'When it encounters another Ditto, it will move faster than normal to duplicate that opponent exactly.', '132.png'),
    (133, 'eevee', 'normal', 'Thanks to its unstable genetic makeup, this special Pokémon conceals many different possible evolutions.', '133.png'),
    (134, 'vaporeon', 'water', 'Its body’s cellular structure is similar to the molecular composition of water. It can melt invisibly in water.', '134.png'),
    (135, 'jolteon', 'electric', 'It accumulates negative ions in the atmosphere to blast out 10,000-volt lightning bolts.', '135.png'),
    (136, 'flareon', 'fire', 'It stores some of the air it inhales in its internal flame pouch, which heats it to over 3,000 degrees Fahrenheit.', '136.png'),
    (137, 'porygon', 'normal', 'In recent years, this species has been very helpful in cyberspace. These Pokémon will go around checking to make sure no suspicious data exists.', '137.png'),
    (138, 'omanyte', 'rock, water', 'An ancient Pokémon that was recovered from a fossil. It swam by cleverly twisting its 10 tentacles about.', '138.png'),
    (139, 'omastar', 'rock, water', 'Its sharp beak rings its mouth. Its shell was too big for it to move freely, so it became extinct.', '139.png'),
    (140, 'kabuto', 'rock, water', 'A Pokémon that was recovered from a fossil. It used the eyes on its back while hiding on the seafloor.', '140.png'),
    (141, 'kabutops', 'rock, water', 'A slim and fast swimmer. It sliced its prey with its sharp sickles and drank the body fluids.', '141.png'),
    (142, 'aerodactyl', 'rock, flying', 'The power of Mega Evolution has completely restored its genes. The rocks on its body are harder than diamond.', '142.png'),
    (143, 'snorlax', 'normal', 'This Pokémon’s stomach is so strong, even eating moldy or rotten food will not affect it.', '143.png'),
    (144, 'articuno', 'ice, flying', 'A legendary bird Pokémon. It freezes water that is contained in winter air and makes it snow.', '144.png'),
    (145, 'zapdos', 'electric, flying', 'This legendary bird Pokémon is said to appear when the sky turns dark and lightning showers down.', '145.png'),
    (146, 'moltres', 'fire, flying', 'A legendary bird Pokémon. As it flaps its flaming wings, even the night sky will turn red.', '146.png'),
    (147, 'dratini', 'dragon', 'Long thought to be a myth, this Pokémon’s existence was only recently confirmed by a fisherman who caught one.', '147.png'),
    (148, 'dragonair', 'dragon', 'According to a witness, its body was surrounded by a strange aura that gave it a mystical look.', '148.png'),
    (149, 'dragonite', 'dragon, flying', 'It is said that this Pokémon lives somewhere in the sea and that it flies. However, these are only rumors.', '149.png'),
    (150, 'mewtwo', 'psychic', 'Psychic power has augmented its muscles. It has a grip strength of one ton and can sprint a hundred meters in two seconds flat!', '150.png'),
    (151, 'mew', 'psychic', 'When viewed through a microscope, this Pokémon’s short, fine, delicate hair can be seen.', '151.png');